services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: st_timescaledb_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timescaledb
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - st_timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  st_timescaledb_data:
    name: st_timescaledb_data
